### ISSUE TITLE
LIBUSB_INCLUDE_DIR build errors with Debian 7.7

### ISSUE THREAD

**Issue by roger-** [libuvc/libuvc#11]
I have libusb-1.0-0-dev installed, but running cmake gives this error:

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBUSB_INCLUDE_DIR
   used as include directory in directory /tmp/uv/libuvc-master
LIBUSB_LIBRARY_NAMES
    linked by target "uvc" in directory /tmp/uv/libuvc-master

-- Configuring incomplete, errors occurred!
```

**Comment by ktossell** [comment]
I just tried it using the debian:wheezy docker image (apt-get install build-essential git cmake libusb-1.0-0-dev && cmake) and didn't get any errors. Had you run cmake before you installed libusb-dev? If so, maybe cmake is caching the NOTFOUND result. If you did install libusb after running cmake, try deleting the build directory and running cmake again.

**Comment by ktossell** [comment]
Though `rm -rf build; apt-get remove libusb-1.0-0-dev; mkdir build; cd build; cmake .. [produces the error you saw]; apt-get install libusb-1.0-0-dev; cmake ..` does work -- with this setup, it manages to find libusb when I rerun cmake.

**Comment by roger-** [comment]
Weird: I removed build/, recreated it and ran cmake but got the same error.
