### ISSUE TITLE
Saving as video

### ISSUE THREAD

**Issue by ArtlyStyles** [libuvc/libuvc#117]
Hi, the sample.c and test.c showed how to capture and processing each individual frame. Is there a easier straightforward way to save the camera stream as video?

**Comment by waddlesplash** [comment]
No; the data that comes from the camera is not in any real standard "video" format (well, MJPEG sort of is, but most people do not want to just save the raw MJPEG.) You will have to use a video codec library to write the frames into a video stream -- FFmpeg, etc.
