### ISSUE TITLE
How to create a uvc_frame_t in c++

### ISSUE THREAD

**Issue by ArtlyStyles** [libuvc/libuvc#119]
How can I create a uvc_frame_t type in c++?

**Comment by jwlodek** [comment]
Import `libuvc.h`, then make sure to link against libuvc at compile time. In the code itself you can just treat it as any C struct - I.E. you can just `malloc` memory for it. Keep in mind that when `start_streaming` is called, it expects a callback function that receives a `uvc_frame_t` pointer as a parameter, and this is generated by the library itself, not by you.

**Comment by waddlesplash** [comment]
You don't `malloc` a `uvc_frame_t*`, it must be made using `uvc_allocate_frame`. This can be called from C++ as well as C.
