### ISSUE TITLE
About  Libuvc 's  STILL Image capture

### ISSUE THREAD

**Issue by yuliang8** [libuvc/libuvc#124]
Hi all:
    The latest version supports still image features. But We found that It Only parse frame description after Initial, cannot to Capture still Image when host send trigger command to device. so we want to know, whether any one give some help about STILL Image function

 Thanks.

**Comment by waddlesplash** [comment]
I'm not quite sure what this is asking...

(Still image support was implemented by @brunomarchand fwiw.)

**Comment by brunomarchand** [comment]
Hello,
Although I did not commit an example how to use the API, here is one from the pull request thread: https://github.com/libuvc/libuvc/pull/89#issuecomment-348552623

I hope this will help.

**Comment by yuliang8** [comment]
Thank you very much 


发自我的 iPhone
