### ISSUE TITLE
Callback exists (-52) Error when getting a frame

### ISSUE THREAD

**Issue by DaveBGld** [libuvc/libuvc#131]
The summary of my code is like this:

```
res = uvc_get_stream_ctrl_format_size(devh, &ctrl, UVC_FRAME_FORMAT_UYVY,  160, 120, 0);
res = uvc_stream_open_ctrl(devh, &strmh, &ctrl);
res = uvc_stream_start(strmh, cb, NULL, 8.0, 0);  // setup callback to cb
```

The the first time I get a frame in the streaming loop with:

`res = uvc_stream_get_frame(strmh, &myFrame, 100);`

I get the error **uvc_stream_get_frame: Callback exists (-52)**   

Your guidance in solving this much appreciated!

**Comment by waddlesplash** [comment]
You cannot both set a callback and use get_frame(). Pick one or the other, but not both. That's what the error message refers to.
