### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by teknotus** [libuvc/libuvc#14]
I cannot find a License file. What are the terms of use, and contribution?

**Comment by ktossell** [comment]
Wow, I'm really surprised that I didn't include a license file. Libuvc is distributed under the BSD 3-clause license. Contributions should be licensed the same way; contributors don't need to assign copyright or anything.

I'll add a license file or a readme entry, but in the meantime, you can find license headers in most of the src/*.c files if you need an in-distribution licensing statement.

**Comment by teknotus** [comment]
Thanks!

**Comment by suertreus** [comment]
Thanks for creating this and making it available under such a generous license =).

Please do add a LICENSE file listing or linking to the text of the license.  Doing so is very helpful to packagers who want to redistribute the code without worry and to businesses who want to build commercial or free products.

**Comment by ktossell** [comment]
Does this work? https://github.com/ktossell/libuvc/commit/68612e2ccbe5889d21aa50c597c3aae2823fb5d4

**Comment by suertreus** [comment]
Perfect, thanks again!
