### ISSUE TITLE
User Callback very slowly @ 10fps when image @1920x1080 30fps MJPEG. Why?

### ISSUE THREAD

**Issue by xiejiezhang** [libuvc/libuvc#145]
User Callback very slowly @ 10fps when image @1920x1080 30fps mjpeg Why?  on the callback function, i  do nothing but printf the time when called.  No convert frame format, No show image; unreasonable!!!

**Comment by waddlesplash** [comment]
Please be more specific and explain the problem in more detail.

**Comment by xiejiezhang** [comment]
becuase the maxplayloader size is too larger. make sure <= 150K
