### ISSUE TITLE
Questions about endpoint selection

### ISSUE THREAD

**Issue by jmachowinski** [libuvc/libuvc#191]
Hi,
I'm using an Azure Kinect which itself is using libuvc in its SDK.

The Azure uses super speed isochronous transfer and is rather unstable in general.
While digging through the code I stumbled over the endpoint selection and have
some question about it.

https://github.com/libuvc/libuvc/blob/master/src/stream.c#L1152
Why isn't the endpoint address checked before as in line 1160 ? Is this a possible bug ?

I'm using the test application and modified it to select MPEG:
```
      res = uvc_get_stream_ctrl_format_size(
          devh, &ctrl, UVC_FRAME_FORMAT_MJPEG, 1280, 720, 30
      );
```
Using debug the camera reports this supported modes : 
```
DEVICE CONFIGURATION (045e:097d/000084210212) ---
[device.c:535] begin uvc_free_device_descriptor
[device.c:548] end uvc_free_device_descriptor
Status: idle
VideoControl:
        bcdUVC: 0x0100
VideoStreaming(1):
        bEndpointAddress: 129
        Formats:
        UncompressedFormat(1)
                  bits per pixel: 16
                  GUID: 5955593200001000800000aa00389b71 (YUY2)
                  default frame: 1
                  aspect ratio: 0x0
                  interlace flags: 00
                  copy protect: 00
                        FrameDescriptor(1)
                          capabilities: 00
                          size: 1280x720
                          bit rate: 442368000-442368000
                          max frame size: 1843200
                          default interval: 1/30
                          interval[0]: 1/30
                          interval[1]: 1/15
                          interval[2]: 1/5
        MJPEGFormat(2)
                  bits per pixel: 0
                  GUID: 4d4a5047000000000000000000000000 (MJPG)
                  default frame: 1
                  aspect ratio: 0x0
                  interlace flags: 00
                  copy protect: 00
 .
.
.
                        FrameDescriptor(6)
                          capabilities: 00
                          size: 1280x720
                          bit rate: 3686400-94371840
                          max frame size: 1048576
                          default interval: 1/30
                          interval[0]: 1/30
                          interval[1]: 1/15
                          interval[2]: 1/5
        UncompressedFormat(3)
                  bits per pixel: 12
                  GUID: 4e56313200001000800000aa00389b71 (NV12)
                  default frame: 1
                  aspect ratio: 0x0
                  interlace flags: 00
                  copy protect: 00
                        FrameDescriptor(1)
                          capabilities: 00
                          size: 1280x720
                          bit rate: 331776000-331776000
                          max frame size: 1382400
                          default interval: 1/30
                          interval[0]: 1/30
                          interval[1]: 1/15
                          interval[2]: 1/5
END DEVICE CONFIGURATION
```

From this descriuption, I would assume, that the max frame size for MJPEG, 720 p is
1048576. But dwMaxVideoFrameSize: is reported as 1843200. (I assume these are the same things).
This is the max frame size for YUY2 720p or NV12 720p. 
Is this correct behavior or a bug ?

Apart from this, the camera behaves somewhat odd, looking at the transfers, using wireshark.
I can see a lot of transfers, that are just zero size, then a full image as series of transfers and then zero transfers again.
Is this 'okayish' behavior, or is something wrong ? 
The behavior of my Logitec USB camera is totally different...

**Comment by mcuee** [comment]
Ref: https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1354
Interesting issue. 
Not so sure the underlying USB chip of the  Azure Kinect.

We tested Super speed isochronous transfer here with libusbk with Cypress FX3 based development board and it seems to work under Windows. libusb itself does not work seems to work well with high speed or SuperSpeed isoc transfer under Windows. 
Ref: https://github.com/mcuee/libusbk/tree/master/BmFW/CYPRESS_FX3

But your issues are different as libusb should work under Linux with SuperSpeed isoc transfer.

**Comment by jmachowinski** [comment]
Thx for your answer. We Finally gave up on the Azure, as we just could not get it to be reliable. So I am closing this ticket.
