### ISSUE TITLE
Return camera name

### ISSUE THREAD

**Issue by pcha75** [libuvc/libuvc#207]
Hello everybody,
is there any function in libuvc which returns a list of names of UVC cameras plugged in the PC? Thank you!

**Comment by jwlodek** [comment]
You can try using this program I wrote for this purpose: https://github.com/areaDetector/ADUVC/tree/master/uvcSupport/cameraDetector

**Comment by pcha75** [comment]
Hi @jwlodek, 
thank you for your reply, this exactly what I was looking for :). Have a good day!
