### ISSUE TITLE
How to compile src files?

### ISSUE THREAD

**Issue by subhash-coder** [libuvc/libuvc#226]
I'm  a begginer, can anyone tell me how  to compile files contained in src directory?

**Comment by jwlodek** [comment]
Did the instructions in the README not work?

```
git clone https://github.com/libuvc/libuvc
cd libuvc
mkdir build
cd build
cmake ..
make && sudo make install
```

**Comment by subhash-coder** [comment]
Only example.c file is being compiled
I'm unable to compile stream.c and test.c

**Comment by jwlodek** [comment]
For the first one, try adding `-lusb-1.0 -lpthread` after `-luvc`. For the other one, to me it seems it's complaining about C++ elements - you're compiling with `gcc`. I'd try `g++` instead

**Comment by subhash-coder** [comment]
thanks @jwlodek  it solved
