### ISSUE TITLE
[Documentation] URL in "About" sidebar section is invalid

### ISSUE THREAD

**Issue by raleighlittles** [libuvc/libuvc#231]
The URL listed on the sidebar: https://ken.tossell.net/libuvc/

doesn't work anymore.

![image](https://user-images.githubusercontent.com/2137201/182693047-c884d0c0-fbf5-41db-b4e7-d49f6039b0f8.png)

**Comment by mcuee** [comment]
Just click "Advanced" and then click "Proceed to ken.tossell.net (unsafe)".

**Comment by ktossell** [comment]
Thanks, fixed this by moving the site to https://libuvc.github.io/ (and redirecting there from the old URL)
