### ISSUE TITLE
[Documentation] URL in README ("developing with UVC") is invalid

### ISSUE THREAD

**Issue by raleighlittles** [libuvc/libuvc#232]
The URL on the README:

https://int80k.com/libuvc/doc/

Is invalid

![image](https://user-images.githubusercontent.com/2137201/182696603-e66d8c92-be03-47a2-b2db-8470cce45b91.png)

**Comment by jwlodek** [comment]
Can confirm. Might want to re-create the docs with doxygen on a docs branch, and enable a `github.io` web page.

**Comment by ktossell** [comment]
Thanks, fixed this by moving the site to https://libuvc.github.io/
