### ISSUE TITLE
glut integration and segmentation fault errors

### ISSUE THREAD

**Issue by mmzarzu** [libuvc/libuvc#24]
I would like to know how to use both libuvc and glut in the same application.
I set a capture callback function using uvc_stream_start() and then set a
display callback function using glutDisplayfunc(), where I read the values set
in the other function. I am getting random segmentation fault errors in the libuvc library
and I do not know if they are caused because memory can be accessed from different
threads simultaneously. Some times the program works and some others does not. 

Should I include a mutex mechanism somehow? Should I use other way to get the frames, such as invoking uvc_stream_get_frame() in the glut loop? It would be great if you could provide me an example on how to do things correctly.

**Comment by waddlesplash** [comment]
Are you still running into problems here?
