### ISSUE TITLE
Use GitHub Pages to host the docs

### ISSUE THREAD

**Issue by FrostKiwi** [libuvc/libuvc#246]
The linked [ken.tossell.net/libuvc/](https://ken.tossell.net/libuvc/) docs are down.
Having proper docs is an important part of discoverability and initially how I found libUVC couple years back. Even though any user can use doxygen to generate it themselves, it's still super important IMO, especially with the excellent code sample on the landing page.

Github pages https://pages.github.com/ allows one free thing to be hosted per project, perfect to host this doc.

Or give me Repo admin access (Since a simple PR is not enough to setup Github pages) for 24h and I will do the following:

- Create a new docs branch
- Upload the generated DoxyGen /doc folder
- point github pages to the docs branch
here is how the settings pages looks in my project:
![image](https://user-images.githubusercontent.com/60887273/205828817-0ecc4b51-8194-48dd-b53f-d7cbfa54a18c.png)

**Comment by ktossell** [comment]
Thanks for suggesting this! The docs are now at https://libuvc.github.io/ and they should get updated automatically
