### ISSUE TITLE
"Current" way for building libuvc for Android

### ISSUE THREAD

**Issue by ffreality** [libuvc/libuvc#258]
I know that there is an example of libuvc but is an old library. Is there any documentation about building libuvc for android ?
currently building libusb is not that hard.

I can't use old gradle versions because I want to make an Unreal Engine plugin for libuvc.

//
I tried to create a C++ android project from Android Studio and added libuvc's CMake as C++ module. I have to define ``LibUSB`` to my environment variables but what is the correct paths for both includes and binaries ?

I am using Windows 11

**Comment by zongren** [comment]
any progress?

**Comment by ffreality** [comment]
nope
