### ISSUE TITLE
How do composite devices support two channels to play video

### ISSUE THREAD

**Issue by HM281099** [libuvc/libuvc#265]
There are two channels under the composite device, and libuvc supports receiving data from both channels at the same time?

thanks!

**Comment by Fly2023-HM** [comment]
![image](https://github.com/libuvc/libuvc/assets/27840645/f0c89ed8-2e6e-4079-a545-dcd9811c3ac4)

**Comment by Fly2023-HM** [comment]
![image](https://github.com/libuvc/libuvc/assets/27840645/e690a7d8-2fc3-4c4f-980a-09625fa81f0c)

1. There are two channels under the composite device
2.  UVC Camera  interface 0 , interface 2      
3. video streams can only be obtained from one camera

**Comment by Fly2023-HM** [comment]
how to  solved it? thanks
