### ISSUE TITLE
Get crash when USB interface gone(unmounted from pc) at uvc_close

### ISSUE THREAD

**Issue by msarafati** [libuvc/libuvc#283]
my code will crash at line uvc_close(devh);
when client remove the camera from PC, the code will call uvc_close(devh) , but It gets:
camera_project: ../../libusb/os/threads_posix.h:58: usbi_mutex_destroy: Assertion `pthread_mutex_destroy(mutex) == 0' failed.

**Comment by yangyagami** [comment]
Update your libusb.

**Comment by yangyagami** [comment]
https://github.com/libuvc/libuvc/issues/url

> my code will crash at line uvc_close(devh); when client remove the camera from PC, the code will call uvc_close(devh) , but It gets: camera_project: ../../libusb/os/threads_posix.h:58: usbi_mutex_destroy: Assertion `pthread_mutex_destroy(mutex) == 0' failed.

**Comment by yangyagami** [comment]
> my code will crash at line uvc_close(devh); when client remove the camera from PC, the code will call uvc_close(devh) , but It gets: camera_project: ../../libusb/os/threads_posix.h:58: usbi_mutex_destroy: Assertion `pthread_mutex_destroy(mutex) == 0' failed.

[https://github.com/libusb/libusb/issues/1199](https://github.com/libusb/libusb/issues/1199)

**Comment by msarafati** [comment]
thanks, the issue is solved, i used:
V1.0.27 for libusb
V0.0.7 for libuvc 
and it works
