### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by v4hn** [libuvc/libuvc#40]
The latest release was tagged in 2014 and quite some development has happened since then.
Especially, libuvc_ros' master branch currently does not build with a released version of libuvc because it misses the `uvc_find_devices` function.

It would be great to have a new version tag for this library!

**Comment by waddlesplash** [comment]
A release was tagged in 2017, so libuvc_ros should now be OK :)

**Comment by v4hn** [comment]
:laughing: This was a long time ago, that's true.
I do not regularly look through all my open issues either...
