### ISSUE TITLE
How to add support for the H.264 format in libuvc ？

### ISSUE THREAD

**Issue by BetterDaZhang** [libuvc/libuvc#66]

**Comment by fengbenpaao** [comment]
this is crazy  issue.     I am try to do it;

**Comment by fantix** [comment]
@fengbenpaao 有进展吗？Any progress?

**Comment by fengbenpaao** [comment]
@fantix   see   https://github.com/saki4510t/UVCCamera/issues/204

**Comment by jinlongxu2018** [comment]
GOOD，我终于得到了H264视频，并且解决了前面几秒H264解码后，花屏/绿屏问题。

**Comment by jinlongxu2018** [comment]
并且增加了UAC音频部分的获取,以及设置不同的音频采样率等,GOOD!
