### ISSUE TITLE
Some trouble installing libuvc

### ISSUE THREAD

**Issue by dongdong0602** [libuvc/libuvc#82]
-- checking for module 'libjpeg'
--   package 'libjpeg' not found
-- Building libuvc with JPEG support.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/exbot/libuvc/build
I can't find the 'libjpeg' package,I don't know how to fix it,should I install some sofeware before I do it?Thank you

**Comment by ktossell** [comment]
That should be ok -- one of the attempts to find libjpeg failed, but another one must have succeeded (most likely cmake was able to find jpeglib.h in /usr)
